name: Deploy So-Close (prof)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js from nvm file
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc
      - name: Install dependencies
        working-directory: frontend
        run: npm ci --if-present
      - name: Build frontend
        working-directory: frontend
        run: npm run build
      - name: Replace api-info.json domain
        run: |
          echo '{"domain": "https://api.so-close.groupe30.socra-sigl.fr"}' > frontend/dist/api-info.json

      - name: Deploy backend files to VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "web-api"
          target: "/home/sigl/so-close"
      - name: install node modules and restart backend service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/sigl/so-close/web-api
            /home/sigl/.nvm/versions/node/v24.3.0/bin/npm install
            sudo systemctl restart so-close-web-api.service

      - name: deploy frontend to VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "frontend/dist"
          target: "/home/sigl/so-close"
